### ISSUE TITLE
little problems

### ISSUE THREAD

**Issue by ishimaruuu** [RocketFoundation/Rocket#211]
guest players can use /p to change him self or other player to admin group, need to remove this permission in permissions.config, but without this they can't see the commands what they have permissions, and in this new version #470 we have problems with /tp, when use this, u get tp to right place but under the map.
sry about my bad english, this is not my 1 language

**Comment by Trojaner25** [comment]
This has been already fixed

**Comment by ishimaruuu** [comment]
oh, but still happening in my server, maybe can be a bad config? can u help me? I still teleporting under the map and players can use /p to change group
