### ISSUE TITLE
Automatic saves throwing exception

### ISSUE THREAD

**Issue by humangenome** [RocketFoundation/Rocket#476]
When setting automatic save from Rocket.Unturned.Config.xml:

> Rocket.Unturned >> Exception in FixedUpdate: System.NullReferenceException: Obje
ct reference not set to an instance of an object
  at SDG.Unturned.LevelGround.save () [0x00000] in <filename unknown>:0
  at SDG.Unturned.Level.save () [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Utils.AutomaticSaveWatchdog.checkTimer () [0x00000] in <fil
ename unknown>:0

It is not saving. Running Rocket v4.6.0.0 and Unturned v3.11.9.1
I tried this with a fresh server (not saved before, no Levels folder) and with an existing server (saved, with Levels folder) both had the same exception thrown.

Rocket.config.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<RocketSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <RCON Enabled="true" Port="25446" Password="changeme" />
  <AutomaticShutdown Enabled="false" Interval="86400" />
  <WebConfigurations Enabled="false" Url="" />
  <WebPermissions Enabled="false" Url="" Interval="180" />
  <LanguageCode>en</LanguageCode>
</RocketSettings>
```

Rocket.Unturned.config.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<UnturnedSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AutomaticSave Enabled="true" Interval="60" />
</UnturnedSettings>
```

**Comment by humangenome** [comment]
I tried this with a fresh server (not saved before, no Levels folder) and with an existing server (saved, with Levels folder)

**Comment by fr34kyn01535** [comment]
Fixed

**Comment by Neefgi** [comment]
It's not fixed for me... I still get this "Splash" error:

![splash](https://cloud.githubusercontent.com/assets/13526894/8970709/f509f6ac-35ff-11e5-8559-f37880d33e7e.png)

**Comment by humangenome** [comment]
@Neefgi That is an unrelated issue.

**Comment by Neefgi** [comment]
@humangenome but it says that the error is Line 3 in my Rocket.Unturned.Config.xml file, and the only coding in that file is my AutomaticSave command.

**Comment by fr34kyn01535** [comment]
Yes, and beside this being unrelated, you malformed it. You managed to break the xml file with just one command config it...

**Comment by Neefgi** [comment]
@fr34kyn01535 how did I malform it? All I did was put in what you told me to do. Is there anyway I can fix it?

**Comment by Kirollos** [comment]
@Neefgi Since you don't know how to fix your xml file, then I'd suggest you deleting your Rocket.Unturned.Config.xml and let rocket regenerate it when you start the server, then edit the value of the interval.

**Comment by Neefgi** [comment]
@Kirollos Oh, thank you! I never considered fixing it that way without deleting all of rocket. That worked! Cheers :)
